name: Test and build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run test
        run: deno test --allow-all
      - name: Build test-tree
        run: make test-tree
