name: Release

on:
  push:
    tags:
      - 'v*'
      
permissions:
  contents: write
env:
  SCRIPT_URL: https://raw.githubusercontent.com/brickpop/test-tree/refs/heads/main/main.ts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run test
        run: deno test --allow-all
      - name: Build test-tree
        run: >
          deno compile --target "aarch64-apple-darwin" -o "test-tree-darwin-aarch64" $SCRIPT_URL &&
          deno compile --target "x86_64-apple-darwin" -o "test-tree-darwin-x86_64" $SCRIPT_URL &&
          deno compile --target "x86_64-unknown-linux-gnu" -o "test-tree-linux-x86_64" $SCRIPT_URL &&
          deno compile --target "aarch64-unknown-linux-gnu" -o "test-tree-linux-aarch64" $SCRIPT_URL &&
          deno compile --target "x86_64-pc-windows-msvc" -o "test-tree-win-x86_64" $SCRIPT_URL &&
          gzip test-tree-darwin-x86_64 &&
          gzip test-tree-darwin-aarch64 &&
          gzip test-tree-linux-x86_64 &&
          gzip test-tree-linux-aarch64 &&
          zip test-tree-win-x86_64.exe.zip test-tree-win-x86_64.exe

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            test-tree-darwin-x86_64.gz
            test-tree-darwin-aarch64.gz
            test-tree-linux-x86_64.gz
            test-tree-linux-aarch64.gz
            test-tree-win-x86_64.exe.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
